// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web_Programlama_Projesi.Data;

#nullable disable

namespace Web_Programlama_Projesi.Migrations
{
    [DbContext(typeof(KuaferContext))]
    [Migration("20241223180215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web_Programlama_Projesi.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalAppointments")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Expertise = "Saç Kesimi",
                            IsActive = true,
                            TotalAppointments = 0,
                            TotalEarnings = 0m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Expertise = "Güzellik Bakımı",
                            IsActive = true,
                            TotalAppointments = 0,
                            TotalEarnings = 0m,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            Expertise = "Masaj",
                            IsActive = true,
                            TotalAppointments = 0,
                            TotalEarnings = 0m,
                            UserId = 5
                        },
                        new
                        {
                            Id = 4,
                            Expertise = "Pedikür/Manikür",
                            IsActive = true,
                            TotalAppointments = 0,
                            TotalEarnings = 0m,
                            UserId = 6
                        });
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AppointmentPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Salons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentPrice = 100m,
                            Expertise = "Saç Kesimi",
                            Name = "Saç Kesim Salonu",
                            WorkingHours = "09:00-17:00"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentPrice = 100m,
                            Expertise = "Güzellik Bakımı",
                            Name = "Güzellik Salonu",
                            WorkingHours = "10:00-18:00"
                        });
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = "10:00",
                            IsAvailable = true,
                            SalonId = 1,
                            StartTime = "1 Ocak 09:00"
                        },
                        new
                        {
                            Id = 2,
                            EndTime = "11:00",
                            IsAvailable = true,
                            SalonId = 1,
                            StartTime = "1 Ocak 10:00"
                        },
                        new
                        {
                            Id = 3,
                            EndTime = "12:00",
                            IsAvailable = true,
                            SalonId = 1,
                            StartTime = "1 Ocak 11:00"
                        },
                        new
                        {
                            Id = 4,
                            EndTime = "13:00",
                            IsAvailable = true,
                            SalonId = 1,
                            StartTime = "1 Ocak 12:00"
                        },
                        new
                        {
                            Id = 5,
                            EndTime = "14:00",
                            IsAvailable = true,
                            SalonId = 1,
                            StartTime = "1 Ocak 13:00"
                        },
                        new
                        {
                            Id = 6,
                            EndTime = "15:00",
                            IsAvailable = true,
                            SalonId = 1,
                            StartTime = "1 Ocak 14:00"
                        },
                        new
                        {
                            Id = 7,
                            EndTime = "16:00",
                            IsAvailable = true,
                            SalonId = 1,
                            StartTime = "1 Ocak 15:00"
                        },
                        new
                        {
                            Id = 8,
                            EndTime = "17:00",
                            IsAvailable = true,
                            SalonId = 1,
                            StartTime = "1 Ocak 16:00"
                        },
                        new
                        {
                            Id = 9,
                            EndTime = "11:00",
                            IsAvailable = true,
                            SalonId = 2,
                            StartTime = "1 Ocak 10:00"
                        },
                        new
                        {
                            Id = 10,
                            EndTime = "12:00",
                            IsAvailable = true,
                            SalonId = 2,
                            StartTime = "1 Ocak 11:00"
                        },
                        new
                        {
                            Id = 11,
                            EndTime = "13:00",
                            IsAvailable = true,
                            SalonId = 2,
                            StartTime = "1 Ocak 12:00"
                        },
                        new
                        {
                            Id = 12,
                            EndTime = "14:00",
                            IsAvailable = true,
                            SalonId = 2,
                            StartTime = "1 Ocak 13:00"
                        },
                        new
                        {
                            Id = 13,
                            EndTime = "15:00",
                            IsAvailable = true,
                            SalonId = 2,
                            StartTime = "1 Ocak 14:00"
                        },
                        new
                        {
                            Id = 14,
                            EndTime = "16:00",
                            IsAvailable = true,
                            SalonId = 2,
                            StartTime = "1 Ocak 15:00"
                        },
                        new
                        {
                            Id = 15,
                            EndTime = "17:00",
                            IsAvailable = true,
                            SalonId = 2,
                            StartTime = "1 Ocak 16:00"
                        },
                        new
                        {
                            Id = 16,
                            EndTime = "18:00",
                            IsAvailable = true,
                            SalonId = 2,
                            StartTime = "1 Ocak 17:00"
                        });
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Password = "123456",
                            Role = "Admin",
                            Username = "B221210042@sakarya.edu.tr"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Password = "123",
                            Role = "User",
                            Username = "user"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Password = "123",
                            Role = "Employee",
                            Username = "Ahmet"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Password = "123",
                            Role = "Employee",
                            Username = "Ayşe"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Password = "123",
                            Role = "Employee",
                            Username = "Mehmet"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Password = "123",
                            Role = "Employee",
                            Username = "Fatma"
                        });
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.Appointment", b =>
                {
                    b.HasOne("Web_Programlama_Projesi.Models.User", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Programlama_Projesi.Models.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Programlama_Projesi.Models.TimeSlot", "TimeSlot")
                        .WithMany("Appointments")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.Employee", b =>
                {
                    b.HasOne("Web_Programlama_Projesi.Models.User", "User")
                        .WithOne("EmployeeDetails")
                        .HasForeignKey("Web_Programlama_Projesi.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.TimeSlot", b =>
                {
                    b.HasOne("Web_Programlama_Projesi.Models.Salon", "Salon")
                        .WithMany("TimeSlots")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.Employee", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.Salon", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.TimeSlot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Web_Programlama_Projesi.Models.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("EmployeeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
